background       = "#08090d"
background-alpha = 0.85
text             = "#c8d2e6"
placeholder      = "#3a4250"
text-error       = "#dc5050"
border           = "rgba(50dcc8ee) rgba(9664dcee) 45deg"
border-active    = "rgba(50dcc8ff) rgba(9664dcff) 45deg"
border-error     = "#dc5050"
border-alpha     = 1.0
selection        = "#50dcc8"
selection-alpha  = 0.45
